### ISSUE TITLE
Observation message week number is not modulu 1024 as the specification suggests

### ISSUE THREAD

**Issue by denniszollo** [swift-nav/piksi_firmware#336] opened 2015-04-10 00:27 UTC
Example obsevation packet shows weeknumber 1839 in the file: http://zazu.ci.swiftnav.com/job/piksi_firmware_Log_Analysis/12264/artifact/serial_link_log_20150409-164416.log

Our specification (and the GPS specification) says that the week number is supposed to be modulu 1024, which should render a week number of 1839 impossible.

**Comment by fnoble** [comment] 2015-04-10 04:25
Our documentation must be wrong. We correct for the GPS week number rollover by adding 1024 so the number we use internally is the true week number rather than the mod 1024 value transmitted in the ephemeris. We must remember to update in 2019 when it rolls over again!

**Comment by fnoble** [comment] 2015-06-25 00:26
Not a bug, closing

**Closed by fnoble** 2015-06-25 00:26 UTC
